# Generated by Django 3.2.8 on 2021-11-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(max_length=100)),
                ('tag_ad', models.TextField(max_length=100)),
                ('count_klients', models.IntegerField(null=True)),
                ('telegram', models.TextField()),
                ('telephone', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
