# Generated by Django 3.2.8 on 2021-11-09 09:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='telegram',
        ),
        migrations.AddField(
            model_name='ad',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='count_klients',
            field=models.IntegerField(null=True, verbose_name='Количество клиентов'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='school',
            field=models.TextField(max_length=100, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='tag_ad',
            field=models.TextField(max_length=100, verbose_name='Вид рекламы'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
