# Generated by Django 3.2.8 on 2021-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20211109_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='school',
        ),
        migrations.AddField(
            model_name='ad',
            name='get',
            field=models.TextField(max_length=100, null=True, verbose_name='Получатель'),
        ),
    ]
