# Generated by Django 3.2.8 on 2021-11-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20211122_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='count_klients',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='tag_ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='telephone',
        ),
    ]
