# Generated by Django 3.2.8 on 2021-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='f_name',
            field=models.TextField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='s_name',
            field=models.TextField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='time',
            field=models.IntegerField(null=True, verbose_name='Количество часов'),
        ),
    ]
