# Generated by Django 3.2.8 on 2021-11-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211109_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
    ]
