# Generated by Django 3.2.8 on 2021-11-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=100)),
                ('check', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='klients.klients')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
