# Generated by Django 3.2.8 on 2021-11-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klients', '0003_auto_20211109_1214'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='klients.klients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(max_length=100, verbose_name='Задача'),
        ),
    ]
