# Generated by Django 3.2.8 on 2021-11-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(max_length=30)),
                ('s_name', models.TextField(max_length=30)),
                ('town', models.TextField(max_length=30)),
                ('school', models.TextField(max_length=30)),
                ('telephone', models.TextField(max_length=30)),
                ('call', models.BooleanField(default=False)),
                ('another_inf', models.TextField(max_length=500)),
                ('status_klienta', models.TextField(max_length=500)),
                ('istochnik', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('servise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.servicemodel')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('f_name',),
            },
        ),
    ]
