# Generated by Django 3.2.8 on 2021-11-09 09:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211109_1214'),
        ('klients', '0002_auto_20211109_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='klients',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klienty', to='klients.statusklienta', verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='istochnik',
            name='istochnik',
            field=models.TextField(max_length=30, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='another_inf',
            field=models.TextField(max_length=500, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='call',
            field=models.BooleanField(default=False, verbose_name='Обзвонить'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='f_name',
            field=models.TextField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='istochnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klienty', to='klients.istochnik', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='s_name',
            field=models.TextField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='school',
            field=models.TextField(max_length=30, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='servise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klienty', to='services.servicemodel', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='klients',
            name='town',
            field=models.TextField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='statusklienta',
            name='status',
            field=models.TextField(max_length=30, verbose_name='Статус Клиента'),
        ),
    ]
