# Generated by Django 3.2.8 on 2021-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klients', '0003_auto_20211109_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusklienta',
            name='status',
            field=models.TextField(max_length=15, verbose_name='Статус Клиента'),
        ),
    ]
