# Generated by Django 3.2.8 on 2021-11-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211109_1214'),
        ('services', '0002_rename_shedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.TextField(max_length=30, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TextField(max_length=30, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество клиентов в группе'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='max_count',
            field=models.IntegerField(null=True, verbose_name='Максимальное количество клиентов в группе'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='name',
            field=models.TextField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Льготная цена'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='service_tag',
            field=models.TextField(max_length=30, verbose_name='Вид услуги'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='teachers.teachers', verbose_name='Преподователь'),
        ),
    ]
