# Generated by Django 3.2.8 on 2021-11-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teachers_options'),
        ('services', '0003_auto_20211109_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=15, verbose_name='')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуги',
            },
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='service_tag',
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='teachers.teachers', verbose_name='Преподователь'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.typeservice', verbose_name='Преподователь'),
        ),
    ]
