# Generated by Django 3.2.8 on 2021-11-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211109_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.typeservice', verbose_name='Вид услуги'),
        ),
    ]
