# Generated by Django 3.2.8 on 2021-11-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество клиентов в группе'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Льготная цена'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.schedule', verbose_name='Расписание'),
        ),
    ]
