# Generated by Django 3.2.8 on 2021-11-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20211110_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='schedule',
        ),
    ]
